# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      r_github_packages: jimhester/covr
      env: R_CODECOV=cover-this-build-only
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release

# safelist
branches:
  only:
  - master
  - dev

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "testing@fake.domain"

after_success:
  - test $R_CODECOV && Rscript -e "covr::codecov()"
