# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false
pandoc_version: 2.3.1

env:
  global:
    # Do not skip tests with skip_on_cran(). Adding this to be explicit for my
    # future self. This is already set by default.
    - NOT_CRAN=true

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=cover-this-build-only
    - os: linux
      r: release
      r_github_packages: ropensci/git2r@v0.21.0
      pandoc_version: 1.19.2.1
    - os: linux
      r: devel
      warnings_are_errors: false
    - os: osx
      r: oldrel
      r_packages: stringi
      addons:
        homebrew:
          packages:
            - libgit2
    - os: osx
      r: release
      r_packages: stringi

# safelist
branches:
  only:
  - master
  - dev

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "testing@fake.domain"

script:
  - R CMD build .
  - travis_wait 30 R CMD check *tar.gz

after_success:
  - travis_wait 30 test $R_CODECOV && Rscript -e "covr::codecov()"
