# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

# safelist
branches:
  only:
  - master
  - dev

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "testing@fake.domain"

after_success:
  - Rscript -e 'covr::codecov()'
