# Some of the CRAN servers have pandoc installed and some do not, thus any test
# that builds an R Markdown file needs to be skipped with skip_on_cran(). This
# CI build does not have pandoc installed, so it will identify any tests that
# require pandoc but aren't skipped.
version: 2
jobs:
  build:
    working_directory: /workflowr
    docker:
      - image: rocker/r-apt:bionic
    branches:
      only:
        - master
        - dev
        - circleci
    steps:
      - checkout
      - run:
          name: Install devtools (and other dependencies) via APT
          command: |
            apt-get update
            apt-get install -y r-cran-devtools
            # System dependencies
            apt-get install -y libxml2-dev qpdf
            # R packages available from c2d4u3.5
            # (can't install rmarkdown since that would install pandoc)
            apt-get install -y r-cran-callr \
                               r-cran-covr \
                               r-cran-fs \
                               r-cran-git2r \
                               r-cran-glue \
                               r-cran-knitr \
                               r-cran-rprojroot \
                               r-cran-rstudioapi \
                               r-cran-stringr \
                               r-cran-testthat \
                               r-cran-whisker \
                               r-cran-withr \
                               r-cran-yaml
            # Dependencies of package spelling (it's not available from c2d4u3.5)
            apt-get install -y r-cran-commonmark \
                               r-cran-hunspell \
                               r-cran-xml2
      - run:
          name: Install package dependencies
          command: r -e "devtools::install_deps(dependencies = TRUE, upgrade = FALSE)"
      - run:
          name: Build and check (without pandoc)
          command: bash build.sh --no-examples --no-manual
      - store_artifacts:
          path: workflowr.Rcheck/
